---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - argoaisupports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - argoaisupports/finalizers
  verbs:
  - update
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - argoaisupports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - authproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - authproviders/finalizers
  verbs:
  - update
- apiGroups:
  - argosupport.argoproj.extensions.io
  resources:
  - authproviders/status
  verbs:
  - get
  - patch
  - update
